version: '3'
services:
  nodejs-test:
    image: node:14.17.3-alpine
    volumes:
      - ./:/src
    working_dir: /src
    depends_on: 
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/microservices
    tty: true
    command: >
       sh -c "npm config set registry https://registry.npm.taobao.org  
       && npm install mongodb@2.2.33
       && /bin/sh"
    # command: ["npm config set registry https://registry.npm.taobao.org"]
    # command: ["npm", "install", "mongodb"]  
  
  db:
    image: mongo:4.4.8
